
# This file is automatically generated, you probably don't want to edit this

AEplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AEplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aeTerm = NULL,
            testGA = NULL,
            testG3 = NULL,
            controlGA = NULL,
            controlG3 = NULL,
            barThm = "Nature", ...) {

            super$initialize(
                package="ClinicalTrialVisualization",
                name="AEplot",
                requiresData=TRUE,
                ...)

            private$..aeTerm <- jmvcore::OptionVariable$new(
                "aeTerm",
                aeTerm,
                suggested=list(
                    "nominal"))
            private$..testGA <- jmvcore::OptionVariable$new(
                "testGA",
                testGA,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..testG3 <- jmvcore::OptionVariable$new(
                "testG3",
                testG3,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..controlGA <- jmvcore::OptionVariable$new(
                "controlGA",
                controlGA,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..controlG3 <- jmvcore::OptionVariable$new(
                "controlG3",
                controlG3,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..barThm <- jmvcore::OptionList$new(
                "barThm",
                barThm,
                options=list(
                    "AAAS",
                    "JAMA",
                    "JCO",
                    "Lancet",
                    "NEJM",
                    "Nature",
                    "UCSF",
                    "TRON",
                    "Simpsons"),
                default="Nature")

            self$.addOption(private$..aeTerm)
            self$.addOption(private$..testGA)
            self$.addOption(private$..testG3)
            self$.addOption(private$..controlGA)
            self$.addOption(private$..controlG3)
            self$.addOption(private$..barThm)
        }),
    active = list(
        aeTerm = function() private$..aeTerm$value,
        testGA = function() private$..testGA$value,
        testG3 = function() private$..testG3$value,
        controlGA = function() private$..controlGA$value,
        controlG3 = function() private$..controlG3$value,
        barThm = function() private$..barThm$value),
    private = list(
        ..aeTerm = NA,
        ..testGA = NA,
        ..testG3 = NA,
        ..controlGA = NA,
        ..controlG3 = NA,
        ..barThm = NA)
)

AEplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AEplotResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        res_plot = function() private$.items[["res_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Adverse Events plots")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Adverse Events plots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="res_plot",
                title="\u4E0D\u826F\u4E8B\u4EF6\u6761\u5F62\u56FE",
                width=800,
                renderFun=".plot"))}))

AEplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AEplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicalTrialVisualization",
                name = "AEplot",
                version = c(1,0,0),
                options = options,
                results = AEplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Adverse Events plots
#'
#' 
#' @param data .
#' @param aeTerm .
#' @param testGA .
#' @param testG3 .
#' @param controlGA .
#' @param controlG3 .
#' @param barThm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$res_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
AEplot <- function(
    data,
    aeTerm,
    testGA,
    testG3,
    controlGA,
    controlG3,
    barThm = "Nature") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("AEplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(aeTerm)) aeTerm <- jmvcore::resolveQuo(jmvcore::enquo(aeTerm))
    if ( ! missing(testGA)) testGA <- jmvcore::resolveQuo(jmvcore::enquo(testGA))
    if ( ! missing(testG3)) testG3 <- jmvcore::resolveQuo(jmvcore::enquo(testG3))
    if ( ! missing(controlGA)) controlGA <- jmvcore::resolveQuo(jmvcore::enquo(controlGA))
    if ( ! missing(controlG3)) controlG3 <- jmvcore::resolveQuo(jmvcore::enquo(controlG3))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(aeTerm), aeTerm, NULL),
            `if`( ! missing(testGA), testGA, NULL),
            `if`( ! missing(testG3), testG3, NULL),
            `if`( ! missing(controlGA), controlGA, NULL),
            `if`( ! missing(controlG3), controlG3, NULL))


    options <- AEplotOptions$new(
        aeTerm = aeTerm,
        testGA = testGA,
        testG3 = testG3,
        controlGA = controlGA,
        controlG3 = controlG3,
        barThm = barThm)

    analysis <- AEplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

