
# This file is automatically generated, you probably don't want to edit this

samplesizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            alpha = 0.05,
            power = 0.8,
            hazardratio = 0.7,
            control = 8,
            enroll = 12,
            permonth = 25,
            ratio = 1,
            followup = 18,
            dropout = 0.05,
            interm = 75, ...) {

            super$initialize(
                package="ClinicalTrialVisualization",
                name="samplesize",
                requiresData=TRUE,
                ...)

            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..hazardratio <- jmvcore::OptionNumber$new(
                "hazardratio",
                hazardratio,
                default=0.7)
            private$..control <- jmvcore::OptionNumber$new(
                "control",
                control,
                default=8)
            private$..enroll <- jmvcore::OptionNumber$new(
                "enroll",
                enroll,
                default=12)
            private$..permonth <- jmvcore::OptionNumber$new(
                "permonth",
                permonth,
                default=25)
            private$..ratio <- jmvcore::OptionNumber$new(
                "ratio",
                ratio,
                default=1)
            private$..followup <- jmvcore::OptionNumber$new(
                "followup",
                followup,
                default=18)
            private$..dropout <- jmvcore::OptionNumber$new(
                "dropout",
                dropout,
                default=0.05)
            private$..interm <- jmvcore::OptionNumber$new(
                "interm",
                interm,
                default=75)

            self$.addOption(private$..alpha)
            self$.addOption(private$..power)
            self$.addOption(private$..hazardratio)
            self$.addOption(private$..control)
            self$.addOption(private$..enroll)
            self$.addOption(private$..permonth)
            self$.addOption(private$..ratio)
            self$.addOption(private$..followup)
            self$.addOption(private$..dropout)
            self$.addOption(private$..interm)
        }),
    active = list(
        alpha = function() private$..alpha$value,
        power = function() private$..power$value,
        hazardratio = function() private$..hazardratio$value,
        control = function() private$..control$value,
        enroll = function() private$..enroll$value,
        permonth = function() private$..permonth$value,
        ratio = function() private$..ratio$value,
        followup = function() private$..followup$value,
        dropout = function() private$..dropout$value,
        interm = function() private$..interm$value),
    private = list(
        ..alpha = NA,
        ..power = NA,
        ..hazardratio = NA,
        ..control = NA,
        ..enroll = NA,
        ..permonth = NA,
        ..ratio = NA,
        ..followup = NA,
        ..dropout = NA,
        ..interm = NA)
)

samplesizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        res_table = function() private$.items[["res_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Estimate Sample Size")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Estimate Sample Size"))
            self$add(jmvcore::Table$new(
                options=options,
                name="res_table",
                title="gsDesign2 - gs_design_ahr \u7EC4\u5E8F\u8BBE\u8BA1\u5206\u6790\u4F30\u8BA1\u7684\u6837\u672C",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"))))}))

samplesizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicalTrialVisualization",
                name = "samplesize",
                version = c(1,0,0),
                options = options,
                results = samplesizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Estimate Sample Size （time-to-event）
#'
#' 
#' @param data .
#' @param alpha .
#' @param power .
#' @param hazardratio .
#' @param control .
#' @param enroll .
#' @param permonth .
#' @param ratio .
#' @param followup .
#' @param dropout .
#' @param interm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$res_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$res_table$asDF}
#'
#' \code{as.data.frame(results$res_table)}
#'
#' @export
samplesize <- function(
    data,
    alpha = 0.05,
    power = 0.8,
    hazardratio = 0.7,
    control = 8,
    enroll = 12,
    permonth = 25,
    ratio = 1,
    followup = 18,
    dropout = 0.05,
    interm = 75) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("samplesize requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- samplesizeOptions$new(
        alpha = alpha,
        power = power,
        hazardratio = hazardratio,
        control = control,
        enroll = enroll,
        permonth = permonth,
        ratio = ratio,
        followup = followup,
        dropout = dropout,
        interm = interm)

    analysis <- samplesizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

