
# This file is automatically generated, you probably don't want to edit this

spiderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "spiderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pid = NULL,
            timeS = NULL,
            lch = NULL,
            clrG = NULL,
            timeM = "\u5929\u6570",
            ynM = "\u662F",
            linThm = "Nature", ...) {

            super$initialize(
                package="ClinicalTrialVisualization",
                name="spider",
                requiresData=TRUE,
                ...)

            private$..pid <- jmvcore::OptionVariable$new(
                "pid",
                pid,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..timeS <- jmvcore::OptionVariable$new(
                "timeS",
                timeS,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..lch <- jmvcore::OptionVariable$new(
                "lch",
                lch,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..clrG <- jmvcore::OptionVariable$new(
                "clrG",
                clrG,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..timeM <- jmvcore::OptionString$new(
                "timeM",
                timeM,
                default="\u5929\u6570")
            private$..ynM <- jmvcore::OptionList$new(
                "ynM",
                ynM,
                options=list(
                    "\u662F",
                    "\u5426"),
                default="\u662F")
            private$..linThm <- jmvcore::OptionList$new(
                "linThm",
                linThm,
                options=list(
                    "AAAS",
                    "JAMA",
                    "JCO",
                    "Lancet",
                    "NEJM",
                    "Nature",
                    "UCSF",
                    "TRON",
                    "Simpsons",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Pastel2",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Nature")

            self$.addOption(private$..pid)
            self$.addOption(private$..timeS)
            self$.addOption(private$..lch)
            self$.addOption(private$..clrG)
            self$.addOption(private$..timeM)
            self$.addOption(private$..ynM)
            self$.addOption(private$..linThm)
        }),
    active = list(
        pid = function() private$..pid$value,
        timeS = function() private$..timeS$value,
        lch = function() private$..lch$value,
        clrG = function() private$..clrG$value,
        timeM = function() private$..timeM$value,
        ynM = function() private$..ynM$value,
        linThm = function() private$..linThm$value),
    private = list(
        ..pid = NA,
        ..timeS = NA,
        ..lch = NA,
        ..clrG = NA,
        ..timeM = NA,
        ..ynM = NA,
        ..linThm = NA)
)

spiderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "spiderResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        res_plot = function() private$.items[["res_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="1期研究 - 蜘蛛图")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Spider Plot for Phase 1 trial"))
            self$add(jmvcore::Image$new(
                options=options,
                name="res_plot",
                title="\u8718\u86DB\u56FE",
                width=1200,
                height=1000,
                renderFun=".plot"))}))

spiderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "spiderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicalTrialVisualization",
                name = "spider",
                version = c(1,0,0),
                options = options,
                results = spiderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Spider Plot
#'
#' 
#' @param data .
#' @param pid .
#' @param timeS .
#' @param lch .
#' @param clrG .
#' @param timeM .
#' @param ynM .
#' @param linThm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$res_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
spider <- function(
    data,
    pid,
    timeS,
    lch,
    clrG,
    timeM = "\u5929\u6570",
    ynM = "\u662F",
    linThm = "Nature") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("spider requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pid)) pid <- jmvcore::resolveQuo(jmvcore::enquo(pid))
    if ( ! missing(timeS)) timeS <- jmvcore::resolveQuo(jmvcore::enquo(timeS))
    if ( ! missing(lch)) lch <- jmvcore::resolveQuo(jmvcore::enquo(lch))
    if ( ! missing(clrG)) clrG <- jmvcore::resolveQuo(jmvcore::enquo(clrG))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pid), pid, NULL),
            `if`( ! missing(timeS), timeS, NULL),
            `if`( ! missing(lch), lch, NULL),
            `if`( ! missing(clrG), clrG, NULL))

    for (v in timeS) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in clrG) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- spiderOptions$new(
        pid = pid,
        timeS = timeS,
        lch = lch,
        clrG = clrG,
        timeM = timeM,
        ynM = ynM,
        linThm = linThm)

    analysis <- spiderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

