
# This file is automatically generated, you probably don't want to edit this

swimmerOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "swimmerOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pid = NULL,
            timeS = NULL,
            lableM = NULL,
            statusM = NULL,
            colorG = NULL,
            ynG = "\u5426",
            timeM = "\u5929\u6570",
            linThm = "Nature", ...) {

            super$initialize(
                package="ClinicalTrialVisualization",
                name="swimmer",
                requiresData=TRUE,
                ...)

            private$..pid <- jmvcore::OptionVariable$new(
                "pid",
                pid,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..timeS <- jmvcore::OptionVariable$new(
                "timeS",
                timeS,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..lableM <- jmvcore::OptionVariable$new(
                "lableM",
                lableM,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..statusM <- jmvcore::OptionVariable$new(
                "statusM",
                statusM,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..colorG <- jmvcore::OptionVariable$new(
                "colorG",
                colorG,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..ynG <- jmvcore::OptionList$new(
                "ynG",
                ynG,
                options=list(
                    "\u5426",
                    "\u662F"),
                default="\u5426")
            private$..timeM <- jmvcore::OptionString$new(
                "timeM",
                timeM,
                default="\u5929\u6570")
            private$..linThm <- jmvcore::OptionList$new(
                "linThm",
                linThm,
                options=list(
                    "AAAS",
                    "JAMA",
                    "JCO",
                    "Lancet",
                    "NEJM",
                    "Nature",
                    "UCSF",
                    "TRON",
                    "Simpsons",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Pastel2",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Nature")

            self$.addOption(private$..pid)
            self$.addOption(private$..timeS)
            self$.addOption(private$..lableM)
            self$.addOption(private$..statusM)
            self$.addOption(private$..colorG)
            self$.addOption(private$..ynG)
            self$.addOption(private$..timeM)
            self$.addOption(private$..linThm)
        }),
    active = list(
        pid = function() private$..pid$value,
        timeS = function() private$..timeS$value,
        lableM = function() private$..lableM$value,
        statusM = function() private$..statusM$value,
        colorG = function() private$..colorG$value,
        ynG = function() private$..ynG$value,
        timeM = function() private$..timeM$value,
        linThm = function() private$..linThm$value),
    private = list(
        ..pid = NA,
        ..timeS = NA,
        ..lableM = NA,
        ..statusM = NA,
        ..colorG = NA,
        ..ynG = NA,
        ..timeM = NA,
        ..linThm = NA)
)

swimmerResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "swimmerResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        res_plot = function() private$.items[["res_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="1期研究 - 泳道图")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Swimmer Plot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="res_plot",
                title="\u6CF3\u9053\u56FE",
                width=600,
                renderFun=".plot"))}))

swimmerBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "swimmerBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicalTrialVisualization",
                name = "swimmer",
                version = c(1,0,0),
                options = options,
                results = swimmerResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Swimmer Plot
#'
#' 
#' @param data .
#' @param pid .
#' @param timeS .
#' @param lableM .
#' @param statusM .
#' @param colorG .
#' @param ynG .
#' @param timeM .
#' @param linThm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$res_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
swimmer <- function(
    data,
    pid,
    timeS,
    lableM,
    statusM,
    colorG,
    ynG = "\u5426",
    timeM = "\u5929\u6570",
    linThm = "Nature") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("swimmer requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pid)) pid <- jmvcore::resolveQuo(jmvcore::enquo(pid))
    if ( ! missing(timeS)) timeS <- jmvcore::resolveQuo(jmvcore::enquo(timeS))
    if ( ! missing(lableM)) lableM <- jmvcore::resolveQuo(jmvcore::enquo(lableM))
    if ( ! missing(statusM)) statusM <- jmvcore::resolveQuo(jmvcore::enquo(statusM))
    if ( ! missing(colorG)) colorG <- jmvcore::resolveQuo(jmvcore::enquo(colorG))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pid), pid, NULL),
            `if`( ! missing(timeS), timeS, NULL),
            `if`( ! missing(lableM), lableM, NULL),
            `if`( ! missing(statusM), statusM, NULL),
            `if`( ! missing(colorG), colorG, NULL))

    for (v in timeS) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in lableM) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in statusM) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in colorG) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- swimmerOptions$new(
        pid = pid,
        timeS = timeS,
        lableM = lableM,
        statusM = statusM,
        colorG = colorG,
        ynG = ynG,
        timeM = timeM,
        linThm = linThm)

    analysis <- swimmerClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

