
# This file is automatically generated, you probably don't want to edit this

waterfallOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "waterfallOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pid = NULL,
            bch = NULL,
            barGP = NULL,
            borM = NULL,
            confM = NULL,
            ongM = NULL,
            tilGP = NULL,
            confS = "C \u786E\u8BA4\u7684CR/PR",
            ongS = "\u2192 \u6CBB\u7597\u4E2D\uFF0C\u00D7 \u6CBB\u7597\u7EC8\u6B62",
            barThm = "Nature",
            tilThm = "AAAS", ...) {

            super$initialize(
                package="ClinicalTrialVisualization",
                name="waterfall",
                requiresData=TRUE,
                ...)

            private$..pid <- jmvcore::OptionVariable$new(
                "pid",
                pid,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..bch <- jmvcore::OptionVariable$new(
                "bch",
                bch,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..barGP <- jmvcore::OptionVariable$new(
                "barGP",
                barGP,
                suggested=list(
                    "nominal"))
            private$..borM <- jmvcore::OptionVariable$new(
                "borM",
                borM,
                suggested=list(
                    "nominal"))
            private$..confM <- jmvcore::OptionVariable$new(
                "confM",
                confM,
                suggested=list(
                    "nominal"))
            private$..ongM <- jmvcore::OptionVariable$new(
                "ongM",
                ongM,
                suggested=list(
                    "nominal"))
            private$..tilGP <- jmvcore::OptionVariables$new(
                "tilGP",
                tilGP,
                suggested=list(
                    "ordinal",
                    "nominal"))
            private$..confS <- jmvcore::OptionString$new(
                "confS",
                confS,
                default="C \u786E\u8BA4\u7684CR/PR")
            private$..ongS <- jmvcore::OptionString$new(
                "ongS",
                ongS,
                default="\u2192 \u6CBB\u7597\u4E2D\uFF0C\u00D7 \u6CBB\u7597\u7EC8\u6B62")
            private$..barThm <- jmvcore::OptionList$new(
                "barThm",
                barThm,
                options=list(
                    "AAAS",
                    "JAMA",
                    "JCO",
                    "Lancet",
                    "NEJM",
                    "Nature",
                    "UCSF",
                    "TRON",
                    "Simpsons",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Pastel2",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="Nature")
            private$..tilThm <- jmvcore::OptionList$new(
                "tilThm",
                tilThm,
                options=list(
                    "AAAS",
                    "JAMA",
                    "JCO",
                    "Lancet",
                    "NEJM",
                    "Nature",
                    "UCSF",
                    "TRON",
                    "Simpsons",
                    "Accent",
                    "Dark2",
                    "Paired",
                    "Pastel1",
                    "Pastel2",
                    "Set1",
                    "Set2",
                    "Set3"),
                default="AAAS")

            self$.addOption(private$..pid)
            self$.addOption(private$..bch)
            self$.addOption(private$..barGP)
            self$.addOption(private$..borM)
            self$.addOption(private$..confM)
            self$.addOption(private$..ongM)
            self$.addOption(private$..tilGP)
            self$.addOption(private$..confS)
            self$.addOption(private$..ongS)
            self$.addOption(private$..barThm)
            self$.addOption(private$..tilThm)
        }),
    active = list(
        pid = function() private$..pid$value,
        bch = function() private$..bch$value,
        barGP = function() private$..barGP$value,
        borM = function() private$..borM$value,
        confM = function() private$..confM$value,
        ongM = function() private$..ongM$value,
        tilGP = function() private$..tilGP$value,
        confS = function() private$..confS$value,
        ongS = function() private$..ongS$value,
        barThm = function() private$..barThm$value,
        tilThm = function() private$..tilThm$value),
    private = list(
        ..pid = NA,
        ..bch = NA,
        ..barGP = NA,
        ..borM = NA,
        ..confM = NA,
        ..ongM = NA,
        ..tilGP = NA,
        ..confS = NA,
        ..ongS = NA,
        ..barThm = NA,
        ..tilThm = NA)
)

waterfallResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "waterfallResults",
    inherit = jmvcore::Group,
    active = list(
        res_text = function() private$.items[["res_text"]],
        res_debug = function() private$.items[["res_debug"]],
        res_plot = function() private$.items[["res_plot"]],
        res_table = function() private$.items[["res_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="1期研究 - 瀑布图")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="res_text",
                title="\u603B\u4F53\u4FE1\u606F"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="res_debug",
                title="debug\u4FE1\u606F"))
            self$add(jmvcore::Image$new(
                options=options,
                name="res_plot",
                title="\u7011\u5E03\u56FE",
                width=1200,
                height=1000,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="res_table",
                title="\u5206\u7EC4\u4FE1\u606F",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="\u4E2A\u6570", 
                        `type`="integer"))))}))

waterfallBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "waterfallBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicalTrialVisualization",
                name = "waterfall",
                version = c(0,0,0),
                options = options,
                results = waterfallResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Waterfall plot
#'
#' 
#' @param data .
#' @param pid .
#' @param bch .
#' @param barGP .
#' @param borM .
#' @param confM .
#' @param ongM .
#' @param tilGP .
#' @param confS .
#' @param ongS .
#' @param barThm .
#' @param tilThm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$res_text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$res_debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$res_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$res_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$res_table$asDF}
#'
#' \code{as.data.frame(results$res_table)}
#'
#' @export
waterfall <- function(
    data,
    pid,
    bch,
    barGP,
    borM,
    confM,
    ongM,
    tilGP,
    confS = "C \u786E\u8BA4\u7684CR/PR",
    ongS = "\u2192 \u6CBB\u7597\u4E2D\uFF0C\u00D7 \u6CBB\u7597\u7EC8\u6B62",
    barThm = "Nature",
    tilThm = "AAAS") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("waterfall requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pid)) pid <- jmvcore::resolveQuo(jmvcore::enquo(pid))
    if ( ! missing(bch)) bch <- jmvcore::resolveQuo(jmvcore::enquo(bch))
    if ( ! missing(barGP)) barGP <- jmvcore::resolveQuo(jmvcore::enquo(barGP))
    if ( ! missing(borM)) borM <- jmvcore::resolveQuo(jmvcore::enquo(borM))
    if ( ! missing(confM)) confM <- jmvcore::resolveQuo(jmvcore::enquo(confM))
    if ( ! missing(ongM)) ongM <- jmvcore::resolveQuo(jmvcore::enquo(ongM))
    if ( ! missing(tilGP)) tilGP <- jmvcore::resolveQuo(jmvcore::enquo(tilGP))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pid), pid, NULL),
            `if`( ! missing(bch), bch, NULL),
            `if`( ! missing(barGP), barGP, NULL),
            `if`( ! missing(borM), borM, NULL),
            `if`( ! missing(confM), confM, NULL),
            `if`( ! missing(ongM), ongM, NULL),
            `if`( ! missing(tilGP), tilGP, NULL))


    options <- waterfallOptions$new(
        pid = pid,
        bch = bch,
        barGP = barGP,
        borM = borM,
        confM = confM,
        ongM = ongM,
        tilGP = tilGP,
        confS = confS,
        ongS = ongS,
        barThm = barThm,
        tilThm = tilThm)

    analysis <- waterfallClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

